### ISSUE TITLE
Event List Responsive Design

### ISSUE THREAD

**Issue by codingMustache** [Nola-Devs/Nola-Devs-v2#104]
### Describe the Problem<

When in mobile the overflow should not exists. and when in desktop view should have an overflow but when page is too small in height

### Describe the Proposed Solution

Adjust CSS with break points

**Comment by Anujjoshi3105** [comment]
Hi @codingMustache, 
I’m interested in taking on this issue. Do you want the results to look similar to the attached images?

![image](https://github.com/user-attachments/assets/009d24b9-cbb5-4452-bb82-55fd27a059bc)
![image](https://github.com/user-attachments/assets/1a81d053-164a-41d9-b27c-211d1885427a)
