### ISSUE TITLE
Event Details View Organizers Broken Icon Links

### ISSUE THREAD

**Issue by colinwilliams91** [Nola-Devs/Nola-Devs-v2#105]
### Describe the Problem

As a user I should be able to click the `n` amount of icons next to each Organizer's tiny profile picture<sup>1</sup>

- From home page click on an event.
- On the right side is a column (a panel?)
- The lower right portion says "Organizers"
  - there are several icons representing links for the organizer
  -  ONLY the email icon works

### References
<sup>1</sup>
![image](https://github.com/user-attachments/assets/e5df477f-3900-4f0a-9e6d-81fc4ec84ea7)

![image](https://github.com/user-attachments/assets/fb46a747-35bb-4991-a288-3b7cc7ef4b2a)

### Describe the Proposed Solution

Not sure...

**Comment by Anujjoshi3105** [comment]
Hi @colinwilliams91, I’m interested in taking on this issue.

**Comment by colinwilliams91** [comment]
Thank you for picking this up! 🙏  @Anujjoshi3105 
I am not familiar with this iteration of the codebase but if you get stuck or have questions you can @ mention me here and I will take a look.
