### ISSUE TITLE
About View Community Organizers Not Sizing Responsively

### ISSUE THREAD

**Issue by colinwilliams91** [Nola-Devs/Nola-Devs-v2#106]
### Describe the Problem<

As a user I want to be able to either see the entire view correctly or be able to scroll

- Navigate to "About" in the top right nav bar
- Examine if you can see the entire view or if it is cut off

### References

![image](https://github.com/user-attachments/assets/76c09567-2ba0-4ea7-8ec3-3983ddee053a)

### Describe the Proposed Solution

Build out style responsivity... media queries? break points? 
Maybe [Flowbite Docs](https://flowbite.com/) has this built in to some components

**Comment by Anujjoshi3105** [comment]
Hi @colinwilliams91,

I noticed the scroll/card design issue similar to #104. I’m interested in helping fix it—thinking of a fixed scroll or enhanced card designs like the attached. 
![image](https://github.com/user-attachments/assets/860aa42a-0a4c-4b7a-9480-b4df0ec964b7)
