### ISSUE TITLE
Add Vercal Analytics

### ISSUE THREAD

**Issue by codingMustache** [Nola-Devs/Nola-Devs-v2#118]
### Describe the Problem

Its missing Vercel Analytics

### References

https://vercel.com/docs/analytics

### Describe the Proposed Solution

We're just not getting analytics

**Comment by mikesamm** [comment]
Updated @vercel/analytics package, added inject script into +layout.svelte. Currently setting up a test deployment on vercel to test the analytics before I submit the PR.
