### ISSUE TITLE
Admin-CMS

### ISSUE THREAD

**Issue by colinwilliams91** [Nola-Devs/Nola-Devs-v2#18]
### <h2>Describe the Problem</h2>

As a site admin (admin/admin) I should be able to update the site. I should be able to assign (add or remove) Permissions and Roles to all other users.

### <h2>References</h2>

Will link screenshots to design. 

### <h2>Describe the Proposed Solution</h2>

Ideally, the page views will look the same with extensible interactivity. (i.e. `edit` or `add` functionality per desired component)

admin/admin/+layout should have 2 tabs Users, Groups

- Users
        - Should be able to Auth people to login to Admin
- Groups
       - Should be able to edit groups Info

An ideal solution is another layer deep of +layout for each Users and Groups. If in group show all the groups if in user show all users. By Clicking one you should be able to get the row on the table and be able to edit any field on that row. the solution doesn't have to be pretty. Not many people will see it.

**Comment by codingMustache** [comment]
If you have smoother solution please share it here.

**Comment by tweezerchef** [comment]
Are we going to try to make our own cms from scratch or will we be using an existing one?  I know little about this but when I was talking to a senior dev about CMS for another project they said to use an existing one rather than create your own from scratch

**Comment by colinwilliams91** [comment]
@tweezerchef I do believe there are some good ways to use and this will be a @codingMustache decision. But, I think the idea as it stands now is that the CMS view will be the same as the public view but it will ALSO expose something like an "edit" button per feature/component that will be able to make simple `CREATE/UPDATE/DELETE` operations to the respective DBs

**Comment by codingMustache** [comment]
Yea we're building one from scratch. The auth is mostly done we have to work on admin Auth and once thats done we have to build out functionality once a user is authenticated. @tweezerchef

**Comment by codingMustache** [comment]
I'm opening this ticket backup to add OAuth using Auth.js and using passkey and email. This will be better than implementing my own. Even though it currently works its just not working as good as I would like it too.

**Comment by mikesamm** [comment]
hey @codingMustache, I'm going to pick up on this.

**Comment by codingMustache** [comment]
Sweet dude, go for it. You can msg me on Slack if you need any help.
