### ISSUE TITLE
ICS Files

### ISSUE THREAD

**Issue by codingMustache** [Nola-Devs/Nola-Devs-v2#24]
A button in the event details that should allow users to download an ics file for individual events. There are some packages to manage this. probs should be marked as good 1st issue 🤷.

*For entire Calendars that can be done with subscribing to a group calendar*

**Comment by codingMustache** [comment]
![Screenshot 2024-03-26 at 8 08 03 AM](https://github.com/Nola-Devs/Nola-Devs-v2/assets/37647527/03e5e142-7602-43ed-8038-f14bd279b826)
 "add to my calendar" should down load the ICS file. should also add a pop up to verify user want to download the file.

**Comment by codingMustache** [comment]
This is located on an event page

**Comment by Aeshus** [comment]
Should we add [`ics` as a dependency](https://www.npmjs.com/package/ics) and use it?

**Comment by codingMustache** [comment]
Thats a good lib, I think @pataran is going to work on this

**Comment by pataran** [comment]
@Aeshus 
I imported the ics library on this issue's branch. Seems to work fine so far.
