### ISSUE TITLE
OAuth

### ISSUE THREAD

**Issue by colinwilliams91** [Nola-Devs/Nola-Devs-v2#26]
This was a suggestion @EtanHey made that we should use Google OAuth rather than a custom implementation of an Auth system that is currently implemented. From the research that I have seen Auth.JS seems like the easiest implementation of this solution. See [Docs](https://authjs.dev)

**Comment by codingMustache** [comment]
I want to revisit this idea and tbh rolling my own auth isn't that nice looking. Looking into Auth JS with email provider and passkey login. Email when user is added and then get passkey to get organizers come to "passwordless" login.

**Comment by codingMustache** [comment]
@Nola-Devs/devs would someone want to pair up and pair program on this?
