### ISSUE TITLE
Dev-CMS

### ISSUE THREAD

**Issue by colinwilliams91** [Nola-Devs/Nola-Devs-v2#27]
### <h2>Describe the Problem</h2>

As a site dev contributor I should be able to submit pictures and links of/for myself.

### <h2>References</h2>

Will link screenshots to design. 

### <h2>Describe the Proposed Solution</h2>

Should expose "Submit" button for designated "Meet the Team" or "Contributors" section that can perform CRUD operations to the contributors table (`users` & `UserModel`?) in the DB. This should be available in the corresponding page view

- Endpoint `Admin/Dev`
  - Add photo
  - Add Links

| Key | Value |
| ---- | ------ |
| Site Name | URL |

This data structure (object) will eventually be passed to the `src/lib/components/icon-parser.svelte` to parse out the correct icon based on the keys

**Comment by colinwilliams91** [comment]
@codingMustache lmk if this lines up with your vision

**Comment by codingMustache** [comment]
This is perfect. As for the tech to add photos. We should use cloudinary, use the SDK and not the API. there is a lot of functionality the SDK offers that the API doesn't and it cleans up a lot of code. When you install this package make sure you read the docs bc most packages should be installed with the -D flag.
