### ISSUE TITLE
Organizer-CMS

### ISSUE THREAD

**Issue by colinwilliams91** [Nola-Devs/Nola-Devs-v2#28]
### <h2>Describe the Problem</h2>

As a group organizer I should see what the Devs see PLUS a section/button to submit group details/information.

### <h2>References</h2>

Will link screenshots to design. 

### <h2>Describe the Proposed Solution</h2>

Should use existing views and expose a button for CRUD to the `groups` (`GroupModel`) table in DB

Data Structures:
Site Name : URL

Input data that will go through Groups Model

**Comment by colinwilliams91** [comment]
@codingMustache for approval

**Comment by colinwilliams91** [comment]
![Image](https://github.com/Nola-Devs/Nola-Devs-v2/assets/92059005/345a5db7-345c-4dfb-a3f8-0ba0a10f291a)

**Comment by codingMustache** [comment]
Organizers and Events will be removed from the schema. Rn Events can be removed till the auth is set up. And then users will be added through the admin side and from there we can an organizer would be associated to a group.
