### ISSUE TITLE
Navbar-UI

### ISSUE THREAD

**Issue by colinwilliams91** [Nola-Devs/Nola-Devs-v2#44]
### <h2>Describe the Problem</h2>

As a user I would like a navbar on the left side of the page to be able to bring me to any of the registered local New Orleans Groups. I would also like some standard navigation options as well such as; "Home", "Calendar Feed", "Add Event", "About us" and "Contact"

### <h2>References</h2>

![Image](https://github.com/Nola-Devs/Nola-Devs-v2/assets/92059005/38d5e791-a914-4c20-a8f0-5f05e740716d)

### <h2>Describe the Proposed Solution</h2>

Setup the html to display the above referenced elements on the left side of the browser page. These should persist across all views like a Layout component. You can use placeholder text if there is no data to grab from the backend/nothing wired up yet.

**Comment by judahsullivan** [comment]
I love the design!

I can certainly make this happen. I am curious of the specs you might want for it. 

Did you want a drawer effect or preferred a fixed design.

I can get started today.🚀

**Comment by colinwilliams91** [comment]
@judahsullivan so it should be static (always visible) for web but on mobile it should be a hamburger button that when pressed displays the navbar. You can apply whatever animations you want to display it with the hamburger press (i know you're the animation master) 

We don't have framer ATM but i can ask if theres any reason why not. For the time being, [Flowbite-svelte has a drawer component](https://flowbite-svelte.com/docs/components/drawer) (not saying it has to be drawer, but at least that's an option. You can pick)

**Comment by HauntedHamburger** [comment]
Hey @judahsullivan!

I'm working on translating styling specs to Flowbite Library.

The sidebar navigation should be:
1. Fixed for desktop screens (though we may need to address situations with massive screens).
2. Drawer for mobile screens.
3. Using the [Flowbite UI](https://flowbite.com/docs/components/sidebar/).

**Comment by colinwilliams91** [comment]
Haha! @HauntedHamburger lol nice timing

**Comment by HauntedHamburger** [comment]
@colinwilliams91 Lol hit em with a quick one two

**Comment by judahsullivan** [comment]
@colinwilliams91 

Awesome! 

Getting started on it now, I can certainly make it happen!

**Comment by judahsullivan** [comment]
## Update



### Where I am so far : 

So far i attempted to create the sidebar as close as possible im sure I can get more precise with the pixels and spacing. Sorry for the water mark at the bottom. Also I added the variables to the tailwind.config so you can use the fonts ,buttoncolor, and cardbg, color theme as they were read in the variables  but still kept the variables there incase you may need in the css. 


#### Questions I have : 


- I have started on the mobile navbar but wanted to know if theres a way i can add the icons to the Local Groups links?
- Also I am Curious is that logo also a Png or Svg? That is the only other thing im possibly missing atm. Which I must say looks so awesome n by the way! 


### Screen shots: 


#### Desktop
![Screenshot 2024-01-18 201227](https://github.com/Nola-Devs/Nola-Devs-v2/assets/106212053/3114321a-bd56-479b-9895-aa7f9fa646e3)
Sorry that's the my browser at the bottom. 

#### Mobile
![Screenshot 2024-01-18 201335](https://github.com/Nola-Devs/Nola-Devs-v2/assets/106212053/0f20d722-26a7-4b4a-b9dc-e5b9bf5cf126)

**Comment by judahsullivan** [comment]
**update 


@colinwilliams91 @codingMustache @HauntedHamburger 


#Menu Nav-Style Question

Is there a specific way you may have wanted the mobile drawer to look? This is what I have thus far.


Also would any one mind helping me understand the functions for the onCLick to add events.

Currently I'm running a addEventlistener in the script which I believe could be written a lot better I just want to make sure I do it correctly 

https://github.com/Nola-Devs/Nola-Devs-v2/assets/106212053/34c2116c-036e-4f9c-baaa-53d1e7d0352e
