### ISSUE TITLE
Loading-Spinner

### ISSUE THREAD

**Issue by colinwilliams91** [Nola-Devs/Nola-Devs-v2#46]
### <h2>Describe the Problem</h2>

As a user I would like to be notified that the page is loading when there is an update to the UI that takes time.

### <h2>References</h2>

[src/routes/(app)/+page.svelte event list element](https://github.com/Nola-Devs/Nola-Devs-v2/blob/main/src/routes/(app)/%2Bpage.svelte#L48C1-L52C10)

```svelte
	<div class="event-list">
		{#if !data}
			<!-- TODO: Add loading animation here -->
			<h1>Loading</h1>
		{:else}
```

### <h2>Describe the Proposed Solution</h2>

Create a generic loading component that can be rendered in the above page and be re-used elsewhere in the application.

**Comment by zablon-oigo** [comment]
Hello, Is the issue still Open? If yes I can tackle this using **awesome loaders**  package to create high-quality 3D loaders that is responsive. I would like to hear your opinion

**Comment by colinwilliams91** [comment]
Hey @zablon-oigo thank you for your interest! I'll tag the lead dev, @codingMustache since it involves a 3rd party lib and some design influence. I appreciate your inspiration and consideration re: your solution :)

**Comment by codingMustache** [comment]
@zablon-oigo what does it look like, out of curiosity? If it matches kind of close to the [Figma](https://www.figma.com/file/OSPgCThKexByNwAN3Ws1rw/Untitled?type=design&node-id=0-1&mode=design&t=O6ArAgFCUF6u1z0v-0) go for it!

**Comment by codingMustache** [comment]
Also one more question @zablon-oigo how did you find this project?

**Comment by zablon-oigo** [comment]
> Also one more question @zablon-oigo how did you find this project?

I searched for **good first issue**  from this site   [goodfirstissue](https://goodfirstissues.com/) and your project popped up the first one clicked on it , familiarized myself with the project and decided to ask if the issue is still open or closed

**Comment by codingMustache** [comment]
Well I'm glad you're hear!!

**Comment by zablon-oigo** [comment]
> Well I'm glad you're hear!!

thank you @codingMustache  I'm happy to be here

**Comment by zablon-oigo** [comment]
> @zablon-oigo what does it look like, out of curiosity? If it matches kind of close to the [Figma](https://www.figma.com/file/P1U1GRxS8sElposHnC6X0S/Nola-Devs-2.0?type=design&mode=design&t=CY4cSWVU1PwNIV0b-1) go for it!

Please explain Im not so familiar with figma app  trying to click on an Image but im having a hard time to navigate around 

![figma](https://github.com/Nola-Devs/Nola-Devs-v2/assets/143833326/6d8dfa39-03d3-4722-8619-87bd894de0c2)

**Comment by codingMustache** [comment]
if you zoom in where the P is, that is what the redesign will eventually look like or at least the aesthetic we're leaning towards. Everything is still a little up in the air but this project is made to replace [noladevs](https://noladevs.org) hold cmd+scroll to zoom

**Comment by zablon-oigo** [comment]
> if you zoom in where the P is, that is what the redesign will eventually look like or at least the aesthetic we're leaning towards. Everything is still a little up in the air but this project is made to replace [noladevs](https://noladevs.org) hold cmd+scroll to zoom

well explained let me give it a try

**Comment by codingMustache** [comment]
Awesome glad to have you on board! Welcome!! Feel free to join the discord too

**Comment by zablon-oigo** [comment]
> @zablon-oigo what does it look like, out of curiosity? If it matches kind of close to the [Figma](https://www.figma.com/file/P1U1GRxS8sElposHnC6X0S/Nola-Devs-2.0?type=design&mode=design&t=CY4cSWVU1PwNIV0b-1) go for it!

Gone through the file and I think what I had in mind to solve this issue will work [loader](https://awesome-loaders.netlify.app/docs/loaders/sunspotloader/)  I would like to here your opinion @codingMustache  @colinwilliams91

**Comment by colinwilliams91** [comment]
> > @zablon-oigo what does it look like, out of curiosity? If it matches kind of close to the [Figma](https://www.figma.com/file/P1U1GRxS8sElposHnC6X0S/Nola-Devs-2.0?type=design&mode=design&t=CY4cSWVU1PwNIV0b-1) go for it!
> 
> Gone through the file and I think what I had in mind to solve this issue will work [loader](https://awesome-loaders.netlify.app/docs/loaders/sunspotloader/) I would like to here your opinion @codingMustache @colinwilliams91

Looks great! Thanks @zablon-oigo. Approved 👍
