### ISSUE TITLE
Event List Scrolling and Height Overflow

### ISSUE THREAD

**Issue by wilsuriel03** [Nola-Devs/Nola-Devs-v2#74]
### <h2>Describe the Problem</h2>

As a user, when I navigate to the events list on the website, I expect to be able to scroll through the entire list of events without any visual or functional constraints. Currently, there is an issue with how the event list handles height and overflow, causing each group to have a fixed height that doesn't adjust to the content within, leading to an improper display and interaction experience.

Please refer to the attached image that demonstrates the problem with the height and overflow of the event list.

### <h2>References</h2>

![image](https://github.com/Nola-Devs/Nola-Devs-v2/assets/66075680/7a65bfe9-362e-4267-81ec-9312fe8ccabc)

### <h2>Describe the Proposed Solution</h2>

A potential solution could involve setting a min-height for each event group container and allowing for overflow-y: auto; so that content can scroll within the container. Additionally, testing with various amounts of content to ensure that the solution is dynamic and responsive across different scenarios would be beneficial.

**Comment by codingMustache** [comment]
Also add snapping to the event cards in the event list
