### ISSUE TITLE
 "Add an Event" Button Lacks Functionality

### ISSUE THREAD

**Issue by wilsuriel03** [Nola-Devs/Nola-Devs-v2#76]
### <h2>Describe the Problem</h2>

As a user or organizer, when clicking the "Add an Event" button, nothing happens. This non-functional button creates confusion and needs to be addressed to improve user experience.

### <h2>References</h2>

![image](https://github.com/Nola-Devs/Nola-Devs-v2/assets/66075680/2465f6b0-776e-454c-a83e-fc3af02bd0e4)

### <h2>Describe the Proposed Solution</h2>

We should implement the actual functionality for adding events, which could be a form that submits a new event or a link to an event submission page. If the feature is not ready, consider temporarily disabling or hiding the button to avoid confusion.

**Comment by codingMustache** [comment]
This should take you to the form to add event, that is connected to the discord webhook that is located in the readme

**Comment by codingMustache** [comment]
that was an accident. I didn't mean to close the issue

**Comment by codingMustache** [comment]
https://github.com/Nola-Devs/Nola-Dev-Site/blob/main/app/components/EventForm.tsx
That is a react example of what's happening

**Comment by codingMustache** [comment]
https://github.com/Nola-Devs/Nola-Dev-Site/blob/main/app/api/route.ts
the POST Request in that file is what's happening on the backend: https://github.com/Nola-Devs/Nola-Dev-Site/blob/main/app/api/route.ts

**Comment by codingMustache** [comment]
The only reason is for moderation and we do want to have events that aren't tried to an organization. Like if there was a convention in town and we don't know about it, we would want someone to fill that form out

**Comment by codingMustache** [comment]
I do like that, we do have to look at how the cron job is adding events to the calendar in order to implement that effectively. The current workflow won't allow that. I can go over it just so you don't have to pour over the code and figure out what its doing
