### ISSUE TITLE
Separate Event Creation from Contact Us Page for Better User Experience

### ISSUE THREAD

**Issue by wilsuriel03** [Nola-Devs/Nola-Devs-v2#77]
### <h2>Describe the Problem</h2>

The current "Contact Us" page includes both contact forms for reaching out to the NOLA Devs team and a form for creating new events. This dual functionality can be confusing for users, as it conflates two distinct actions — contacting and event submission — into a single page. 

### <h2>References</h2>

![image](https://github.com/Nola-Devs/Nola-Devs-v2/assets/66075680/717fd465-66e5-4f97-9a11-5c9b9a3d5257)

reference this issue: https://github.com/Nola-Devs/Nola-Devs-v2/issues/76

### <h2>Describe the Proposed Solution</h2>

To enhance the user interface and separate concerns, I propose we:

- **Restrict the "Contact Us" Page**: Ensure that the "Contact Us" page is solely dedicated to reaching out to the NOLA Devs team for inquiries, support, or feedback.

- **Dedicated Event Submission Flow**: Create a separate page or a modal dialog for "Create an Event". This will streamline the user experience, making it clear where to submit event details.

**Comment by codingMustache** [comment]
This was my fault adding it to the Figma bc I didn't see the "+ Add Event" button and I wasn't sure where to add the event form
